version: 1.2.1-alpha.3.{build}
image: Visual Studio 2022

build:
  project: SQLStreamStore.sln
  verbosity: minimal
  publish_nuget: true             # package projects with .nuspec files and push to artifacts
before_build:
  - cmd: dotnet restore --verbosity m
nuget:
  project_feed: true
install:
  - ps: |
      Invoke-WebRequest -Uri 'https://dot.net/v1/dotnet-install.ps1' -UseBasicParsing -OutFile "$env:temp\dotnet-install.ps1"
      & $env:temp\dotnet-install.ps1 -Architecture x64 -Version '10.0.102' -InstallDir "$env:ProgramFiles\dotnet"